import { Inter } from "next/font/google";
import "./globals.css";
import Logo from "./pages/Logo/page"
import Navbar from "./pages/Navbar/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Inscription",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet"></link>

      </head>

      <body className={inter.className}>
        <Navbar></Navbar>
        <div className="flex flex-col h-max">
          {children}
        </div>

        {/* <div className="fixed bottom-0 right-0  m-4">  </div> */}
        {/* <Logo></Logo> */}
      </body>

    </html>
  );
}

// const paths = posts.map(post => ({
//   params: { id: post.id },
// }))

// const paths = posts.map((post) => ({
//   params: { id: post.id },
// }))